# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: TomoBEAR wiki

theme:
  name: material
  features:
    # use tabs as a navugation system
    - navigation.tabs
    # add "back to top" button
    - navigation.top
  icon:
    # choice of icon in the page header
    repo: fontawesome/brands/github
  palette:
    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# enables admonitions, allows to make them collapsible
# and to nest arbitrary content inside admonitions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# link to the repo in the page header
repo_url: https://github.com/KudryashevLab/TomoBEAR
repo_name: KudryashevLab/TomoBEAR

# link to the repo and choice of the icon in the page footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KudryashevLab/TomoBEAR

# wiki structure
nav:
  - Home: home.md
  - Getting started:
    - TomoBEAR structure: getting_started/tomobear-structure.md
    - Installation and setup: getting_started/installation-and-setup.md
    - Quick start guide: getting_started/quick-start-guide.md
    - Frequently asked questions: getting_started/frequently-asked-questions.md
  - Usage:
    - Tutorials: usage/tutorials.md
    - Usage examples: usage/usage-examples.md
    - Execution Environments: usage/execution-environments.md
  - Modules:
    - Modules overview: modules/modules-overview.md
    - Special modules: modules/special-modules.md
    - Preprocessing & reconstruction:
      - Overview: modules/preprocessing-and-reconstruction.md
      - CreateStacks: modules/preprocessing_and_reconstruction/create-stacks.md
    - Sub-tomogram averaging:
      - Overview: modules/subtomogram-averaging.md
      - DynamoAlignmentProject: modules/subtomogram_averaging/dynamo-alignment-project.md
    - Old modules description: modules/old-modules.md
  - Contributing:
    - Report/fix bug: contributing/report-or-fix-bug.md
    - Suggest a new module: contributing/contribute-module.md
    - To-do's: contributing/to-do.md
  - About TomoBEAR & us:
    - KudryashevLab: about/kudryashev-lab.md
    - Authors & contributions: about/authors-and-contributions.md
    - Publications & citations: about/publications-and-citations.md
  - References:
    - Embedded software: references/embedded-software.md
    - Included algorithms: references/included-algorithms.md
