name: "Mirror docs/ to repo.wiki"

# Run on changes to the `docs` directory on the `main` branch
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: TomoBEAR
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: "ArtsemiY/TomoBEAR-test"
          path: TomoBEAR-test.wiki
      - name: Copy wiki files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Wiki mirror"
          cp $GITHUB_WORKSPACE/docs/*.md $GITHUB_WORKSPACE/TomoBEAR-test.wiki
          cd $GITHUB_WORKSPACE/TomoBEAR-test.wiki
          git add .
          # only commit if there are changes
          git diff-index --quiet HEAD -- || git commit -m "sync from docs/"
          git push
